load(":expander_test.bzl", "expander_test")

expander_test(
    name = "no_expansion",
    expand = [
        "Hello",
        "World!",
        "I am a test.",
        "export $$PATH=$$PATH:/new/path",
        "$$",
    ],
)

expander_test(
    name = "standard_make_variables",
    expand = [
        "$(TARGET_CPU)",
        "$(COMPILATION_MODE)",
        "$(BINDIR)",
        "$(GENDIR)",
    ],
)
